source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SocialLib_Example', :exclusive => true do
  pod "SocialLib", :path => "../"
end

target 'SocialLib_Tests', :exclusive => true do
  pod "SocialLib", :path => "../"

  
end
