source 'https://github.com/CocoaPods/Specs.git'

target 'SocialLib_Example', :exclusive => true do
  pod "SocialLib", :path => "../"
end

target 'SocialLib_Tests', :exclusive => true do
  pod "SocialLib", :path => "../"
  
end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        end
    end
end
